spring.application.name=notification-service

server.port=8085

spring.datasource.url=jdbc:postgresql://${NOTIFICATION_DB_HOST}:${NOTIFICATION_DB_PORT}/${NOTIFICATION_DB_NAME}
spring.datasource.username=${NOTIFICATION_DB_USER}
spring.datasource.password=${NOTIFICATION_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


jwt.access.secret=${JWT_ACCESS_SECRET}
app.frontend-url=${FRONTEND_URL}


spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

kafka.topic.user-registered=user-registered-topic
kafka.topic.payment-success=payment-succeeded
kafka.topic.payment-failed=payment-failed
kafka.topic.booking-expired=booking-expired
kafka.topic.booking-canceled=booking-canceled

spring.kafka.consumer.group-id=notification-group


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

logging.level.com.sorokaandriy.notification_service=INFO