spring.application.name=auth-service

server.port=8081


spring.datasource.url=jdbc:postgresql://${AUTH_DB_HOST}:${AUTH_DB_PORT}/${AUTH_DB_NAME}
spring.datasource.username=${AUTH_DB_USER}
spring.datasource.password=${AUTH_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


jwt.access.secret=${JWT_ACCESS_SECRET}
jwt.refresh.secret=${JWT_REFRESH_SECRET}
jwt.access-expiration=${JWT_ACCESS_EXPIRATION}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION}


spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

kafka.topic.user-registered=user-registered-topic




logging.level.com.sorokaandriy.auth_service=INFO

app.frontend-url=${FRONTEND_URL}