spring.application.name=event-service

server.port=8082

spring.datasource.url=jdbc:postgresql://${EVENT_DB_HOST}:${EVENT_DB_PORT}/${EVENT_DB_NAME}
spring.datasource.username=${EVENT_DB_USER}
spring.datasource.password=${EVENT_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.access.secret=${JWT_ACCESS_SECRET}
app.frontend-url=${FRONTEND_URL}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.consumer.group-id=event-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false


logging.level.com.sorokaandriy.event_service=INFO


event.prices.vip=500.00
event.prices.a=350.00
event.prices.b=250.00
event.prices.default=200.00
